import '../style.css';
import {task1} from "./tasks/task1";
import {task2} from "./tasks/task2";
import {task3} from "./tasks/task3a";
import {task4} from "./tasks/task4";
import {task5} from "./tasks/task5";
import {task6} from "./tasks/task6";
import {task7} from "./tasks/task7a";
import {task8} from "./tasks/task8";
import {task9} from "./tasks/task9";
import {task10} from "./tasks/task10";
import {task12} from "./tasks/task12";
import {task11} from "./tasks/task11";
import {task13} from "./tasks/task13";
import {task14} from "./tasks/task14";
import {task15} from "./tasks/task15";
import {task16} from "./tasks/task16";

// task1();
// task2();
// task3();
// task4();
// task5();
// task6();
// task7();
// task8();
// task9();
// task10();
// task11();
// task12();
// task13();
// task14();
// task15();
task16();